[package]
name = "meshless_voronoi"
description = "An implementation of the Meshless Voronoi algorithm in rust."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["voronoi","graphics","physics","diagram"]
categories = ["graphics","physics"]
exclude = ["plot_vortess.py"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"
rstar = "0.9.3"
rayon = "1.6.1"

[dev-dependencies]
rand = "0.8"
float-cmp = "0.9"