[package]
name = "meshless_voro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"
rstar = "0.9.3"
rayon = "1.6.1"

[dev-dependencies]
rand = "0.8"
float-cmp = "0.9"