[package]
name = "meshless_voro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"

[dev-dependencies]
rand = "0.8"
float-cmp = "0.9"